$('#home-owl-carousel,#product-owl-carousel,#categoryproduct-owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1.3
        },
        600:{
            items:3
        },
        1000:{
            items:3.5
        }
    }
})